<?php if ($this->pageCount): ?>
    <nav>
        <ul class="pagination">
            <!-- Previous page link -->
            <?php if (isset($this->previous)): ?>
                <li class="page-item">
                    <a class="page-link"
                       href="<?= $this->url($this->route, [], ['query' => ['page' => $this->previous]]) ?>">
                        Previous
                    </a>
                </li>
            <?php else: ?>
                <li class="page-item disabled">
                    <span class="page-link">Previous</span>
                </li>
            <?php endif ?>

            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page !== $this->current): ?>
                    <li class="page-item">
                        <a class="page-link"
                           href="<?= $this->url($this->route, [], ['query' => ['page' => $page]]) ?>">
                            <?= $page ?>
                        </a>
                    </li>
                <?php else: ?>
                    <li class="page-item active" aria-current="page">
                        <span class="page-link"><?= $page ?></span>
                    </li>
                <?php endif ?>
            <?php endforeach ?>

            <!-- Next page link -->
            <?php if (isset($this->next)): ?>
                <li class="page-item">
                    <a class="page-link"
                       href="<?= $this->url($this->route, [], ['query' => ['page' => $this->next]]) ?>">
                        Next
                    </a>
                </li>
            <?php else: ?>
                <li class="page-item disabled">
                    <span class="page-link">Next</span>
                </li>
            <?php endif ?>
        </ul>
    </nav>
<?php endif ?>