<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 * @var Album\Model\Album $album
 */

$title = $this->translate('Delete album');
$url   = $this->url('album', ['action' => 'delete', 'id' => $album->id]);

$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    <?= $this->translate('Are you sure that you want to delete') ?>:
    "<?= $this->escapeHtml($album->title) ?>" <?= $this->translate('by') ?>
    "<?= $this->escapeHtml($album->artist) ?>"?
</p>

<form action="<?= $url ?>" method="post">
    <div class="form-group">
        <input type="hidden" name="id" value="<?= (int) $album->id ?>" />
        <input type="submit" class="btn btn-danger" name="del" value="<?= $this->translate('yes') ?>" />
        <input type="submit" class="btn btn-success" name="del" value="<?= $this->translate('no') ?>" />
    </div>
</form>
