<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 * @var Laminas\Paginator\Paginator $paginator
 */
$title = $this->translate('My albums');
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('album', ['action' => 'add']) ?>"><?= $this->translate('Add new album') ?></a>
</p>

<table class="table">
    <tr>
        <th><?= $this->translate('Title') ?></th>
        <th><?= $this->translate('Artist') ?></th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($paginator as $album) : ?>
        <tr>
            <td><?= $this->escapeHtml($album->title) ?></td>
            <td><?= $this->escapeHtml($album->artist) ?></td>
            <td>
                <a href="<?= $this->url('album', ['action' => 'edit', 'id' => $album->id]) ?>"><?= $this->translate('Edit') ?></a>
                <a href="<?= $this->url('album', ['action' => 'delete', 'id' => $album->id]) ?>"><?= $this->translate('Delete') ?></a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>

<?= $this->paginationControl(
// The paginator object:
    $this->paginator,
    // The scrolling style:
    'sliding',
    // The partial to use to render the control:
    'partial/paginator',
    // The route to link to when a user clicks a control link:
    ['route' => 'album']
) ?>